
import React, { useState, useMemo, useEffect } from 'react';
import type { AiState, Agent, Consensus, GroundingChunk } from '../types';

/**
 * Determines the inline CSS styles for an AgentCard based on its status.
 * This provides immediate visual feedback on an agent's state (e.g., pulsing when working, shaking on error).
 * @param {Agent} agent - The agent object containing status and color information.
 * @returns {React.CSSProperties} A style object to be applied to the agent card's container.
 */
const getAgentCardStyle = (agent: Agent): React.CSSProperties => {
    switch (agent.status) {
        case 'working':
            return {
                borderColor: agent.color,
                boxShadow: `0 0 25px ${agent.color}99`,
                animation: 'agentPulse 2s infinite ease-in-out',
            };
        case 'error':
            return {
                borderColor: '#CF6679',
                boxShadow: `0 0 15px #CF667999`,
                animation: 'agentError 0.5s linear',
            };
        case 'idle':
            return {
                borderColor: agent.color,
                animation: 'agentIdle 3s infinite ease-in-out',
            };
        case 'done':
            return {
                borderColor: agent.color,
                opacity: 0.9,
            };
        default:
            return {
                borderColor: agent.color,
            };
    }
};

/**
 * A UI component representing a single AI agent. It displays the agent's name,
 * subtitle, current status, and a status message or content. Visual styling is
 * dynamically applied based on the agent's status to provide clear feedback.
 * @param {{ agent: Agent }} props - Component props containing the agent data.
 * @returns {React.ReactElement} The rendered agent card element.
 */
const AgentCard: React.FC<{ agent: Agent }> = ({ agent }) => (
    <div
        className={`agent-card bg-[#313328] rounded-lg p-3 mb-2 border-l-4 transition-all duration-300`}
        style={getAgentCardStyle(agent)}
    >
        <div
            className="agent-title font-bold text-sm mb-1"
            style={{ color: agent.status === 'error' ? '#CF6679' : agent.color }}
        >
            {agent.title}
        </div>
        <div className="agent-subtitle text-xs text-[#999966] mb-1.5">{agent.subtitle}</div>
        <div className="agent-content text-xs min-h-[20px] flex items-center">
            {agent.status === 'working' && (
                <div className="quantum-spinner w-4 h-4 inline-block mr-1.5 relative">
                    <div className="absolute w-full h-full border-2 border-transparent border-t-[#03DAC6] rounded-full quantum-spinner::before"></div>
                    <div className="absolute w-full h-full border-2 border-transparent border-b-[#BB86FC] rounded-full quantum-spinner::after"></div>
                </div>
            )}
            {agent.status === 'done' && (
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-4 w-4 mr-1.5 text-green-400 flex-shrink-0"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                >
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
            )}
            {agent.status === 'error' && (
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-4 w-4 mr-1.5 text-red-500 flex-shrink-0"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                >
                    <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
                    />
                </svg>
            )}
            {agent.content}
        </div>
    </div>
);

/**
 * A panel that displays the results of a multi-agent consensus process.
 * It lists all the code candidates generated by the agents, highlighting the top-scoring
 * candidate and showing which agents contributed to each version.
 * @param {{ consensus: Consensus }} props - Component props containing the consensus result data.
 * @returns {React.ReactElement} The rendered consensus results panel.
 */
const ConsensusPanel: React.FC<{ consensus: Consensus }> = ({ consensus }) => (
    <div className="consensus-panel bg-[#313328] border border-[#BB86FC] rounded-lg p-3.5 mt-4 max-h-72 overflow-y-auto">
        <div className="consensus-header font-bold text-[#BB86FC] mb-2.5 flex justify-between items-center">
            <span>Multi-Agent Consensus Results</span>
            <span className="bg-[#BB86FC] text-white px-1.5 py-0.5 rounded-full text-xs">Score: {consensus.score}</span>
        </div>
        <div>
            {consensus.allCandidates.map((c, i) => (
                <div
                    key={i}
                    className={`candidate-item bg-white/5 rounded p-2 mb-2 border-l-4 ${
                        i === 0 ? 'border-l-[#4ac94a] bg-green-500/10' : 'border-l-[#03DAC6]'
                    }`}
                >
                    <div className="text-xs text-[#999966] flex justify-between mb-1">
                        <span>{c.agents.join(', ')}</span>
                        <span>Count: {c.count}</span>
                    </div>
                    <div className="text-xs font-mono whitespace-pre-wrap max-h-20 overflow-hidden text-ellipsis">
                        {c.content.substring(0, 200)}
                        {c.content.length > 200 ? '...' : ''}
                    </div>
                </div>
            ))}
        </div>
    </div>
);

/**
 * A panel that displays the web sources used for grounding a Gemini API response.
 * It lists the titles and links to the web pages that the AI used to formulate its answer,
 * providing transparency and allowing for source verification.
 * @param {{ chunks: GroundingChunk[] }} props - Component props containing the array of grounding chunks.
 * @returns {React.ReactElement} The rendered grounding sources panel.
 */
const GroundingPanel: React.FC<{ chunks: GroundingChunk[] }> = ({ chunks }) => (
    <div className="grounding-panel bg-yellow-900/20 border border-[#FFD54F] rounded-lg p-3.5 mt-4">
        <div className="flex items-center gap-2 font-bold text-[#FFD54F] mb-3">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path d="M10 3.5a1.5 1.5 0 01.5 2.915V9.5a1.5 1.5 0 01-3 0V6.415A1.5 1.5 0 0110 3.5z" />
                <path d="M10 18a8 8 0 100-16 8 8 0 000 16zM2 10a8 8 0 1116 0 8 8 0 01-16 0z" />
            </svg>
            <span>Grounded on Real-Time Google Search</span>
        </div>
        <ol className="list-decimal list-inside text-xs space-y-2 pl-1">
            {chunks.map(
                (chunk, i) =>
                    chunk.web && (
                        <li key={i} className="truncate">
                            <a
                                href={chunk.web.uri}
                                target="_blank"
                                rel="noopener noreferrer"
                                title={chunk.web.title || chunk.web.uri}
                                className="text-sky-400 hover:underline hover:text-sky-300 transition-colors"
                            >
                                {chunk.web.title || chunk.web.uri}
                            </a>
                        </li>
                    )
            )}
        </ol>
    </div>
);

/**
 * Generates a diff between two strings using a simplified LCS (Longest Common Subsequence) algorithm.
 * @param {string} oldStr The original string.
 * @param {string} newStr The new string.
 * @returns {Array<{type: 'common' | 'added' | 'removed', text: string}>} An array of diff objects.
 */
const generateDiff = (oldStr: string, newStr: string) => {
    const oldLines = oldStr.split('\n');
    const newLines = newStr.split('\n');
    const M = oldLines.length;
    const N = newLines.length;
    const dp = Array.from({ length: M + 1 }, () => Array(N + 1).fill(0));

    for (let i = 1; i <= M; i++) {
        for (let j = 1; j <= N; j++) {
            if (oldLines[i - 1] === newLines[j - 1]) {
                dp[i][j] = dp[i - 1][j - 1] + 1;
            } else {
                dp[i][j] = Math.max(dp[i - 1][j], dp[i][j - 1]);
            }
        }
    }

    const diff = [];
    let i = M,
        j = N;
    while (i > 0 || j > 0) {
        if (i > 0 && j > 0 && oldLines[i - 1] === newLines[j - 1]) {
            diff.unshift({ type: 'common' as const, text: oldLines[i - 1] });
            i--;
            j--;
        } else if (j > 0 && (i === 0 || dp[i][j - 1] >= dp[i - 1][j])) {
            diff.unshift({ type: 'added' as const, text: newLines[j - 1] });
            j--;
        } else if (i > 0 && (j === 0 || dp[i][j - 1] < dp[i - 1][j])) {
            diff.unshift({ type: 'removed' as const, text: oldLines[i - 1] });
            i--;
        } else {
            break;
        }
    }
    return diff;
};

/**
 * A component to display a visual diff between two blocks of text.
 * @param {object} props The component props.
 * @param {string} props.before The original text.
 * @param {string} props.after The new text.
 * @returns {React.ReactElement} The rendered diff view.
 */
const DiffViewer: React.FC<{ before: string; after: string }> = ({ before, after }) => {
    const diff = useMemo(() => generateDiff(before, after), [before, after]);

    return (
        <pre className="text-xs font-mono whitespace-pre-wrap text-slate-300">
            <code>
                {diff.map((line, index) => {
                    const lineClasses = {
                        added: 'bg-green-500/20',
                        removed: 'bg-red-500/20',
                        common: '',
                    };
                    const prefixes = { added: '+', removed: '-', common: ' ' };
                    return (
                        <div key={index} className={lineClasses[line.type]}>
                            <span className="select-none inline-block w-4 text-center">{prefixes[line.type]}</span>
                            <span>{line.text}</span>
                        </div>
                    );
                })}
            </code>
        </pre>
    );
};

/**
 * Highlights occurrences of a query within a text string by wrapping them in <mark> tags.
 * @param {string} text - The source text (e.g., a block of code).
 * @param {string} query - The search term to highlight.
 * @returns {string} An HTML string with matches highlighted.
 */
const highlightMatches = (text: string, query: string): string => {
    if (!query) return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    const escapedText = text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    const escapedQuery = query.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
    const regex = new RegExp(`(${escapedQuery})`, 'gi');
    return escapedText.replace(regex, `<mark class="bg-yellow-500/50 rounded px-0.5">$1</mark>`);
};

interface AiResponsePanelProps {
    isOpen: boolean;
    aiState: AiState;
    onClose: () => void;
    onApplyCode: (code: string) => void;
    onCopyCode: (code: string) => void;
    originalCode: string;
}

/**
 * The main container panel for displaying all AI-related responses.
 * This component manages the presentation of agent statuses, consensus results,
 * grounding information, and the final generated code. It includes a search bar
 * to filter the displayed information, and provides actions to apply or copy the
 * generated code to the editor.
 * @param {AiResponsePanelProps} props - The component props.
 * @returns {React.ReactElement | null} The rendered AI response panel or null if not open.
 */
export const AiResponsePanel: React.FC<AiResponsePanelProps> = ({
    isOpen,
    aiState,
    onClose,
    onApplyCode,
    onCopyCode,
    originalCode,
}) => {
    const [searchQuery, setSearchQuery] = useState('');
    const [viewMode, setViewMode] = useState<'code' | 'diff'>('code');

    useEffect(() => {
        if (isOpen) {
            setViewMode('code');
        }
    }, [isOpen]);

    if (!isOpen) return null;

    const codeToActOn = aiState.consensus?.selectedCandidate ?? aiState.generatedCode;
    const lowerCaseQuery = searchQuery.toLowerCase();

    const filteredAgents = aiState.agents.filter((agent) => {
        if (!searchQuery) return true;
        const contentString = typeof agent.content === 'string' ? agent.content : '';
        return (
            agent.title.toLowerCase().includes(lowerCaseQuery) ||
            agent.subtitle.toLowerCase().includes(lowerCaseQuery) ||
            contentString.toLowerCase().includes(lowerCaseQuery)
        );
    });

    const filteredConsensus = aiState.consensus
        ? {
              ...aiState.consensus,
              allCandidates: aiState.consensus.allCandidates.filter((c) => {
                  if (!searchQuery) return true;
                  return (
                      c.content.toLowerCase().includes(lowerCaseQuery) ||
                      c.agents.join(', ').toLowerCase().includes(lowerCaseQuery)
                  );
              }),
          }
        : null;

    const filteredGroundingChunks = aiState.groundingChunks?.filter((chunk) => {
        if (!searchQuery) return true;
        if (!chunk.web) return false;
        return (
            (chunk.web.title || '').toLowerCase().includes(lowerCaseQuery) ||
            chunk.web.uri.toLowerCase().includes(lowerCaseQuery)
        );
    });

    return (
        <div className="fixed bottom-20 right-5 w-[500px] max-h-[600px] bg-[#313328] border border-[#4ac94a] rounded-lg flex flex-col z-40 shadow-2xl overflow-hidden">
            <div className="p-4 border-b border-gray-700 flex items-center gap-3 sticky top-0 bg-[#313328]/95 backdrop-blur-sm z-10">
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-5 w-5 text-gray-500 flex-shrink-0"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                >
                    <path
                        fillRule="evenodd"
                        d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                        clipRule="evenodd"
                    />
                </svg>
                <input
                    type="search"
                    placeholder="Filter agents, code, or results..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="w-full bg-transparent text-sm text-[#f0f0e0] placeholder-gray-500 focus:ring-0 outline-none border-none p-0"
                    aria-label="Filter AI responses"
                />
                <button
                    onClick={onClose}
                    className="text-[#999966] text-2xl hover:text-red-500 transition-colors"
                    aria-label="Close AI panel"
                >
                    &times;
                </button>
            </div>

            <div className="overflow-y-auto p-4">
                {filteredAgents.map((agent) => (
                    <AgentCard key={agent.name} agent={agent} />
                ))}

                {codeToActOn && (
                    <div className="code-container bg-black/30 rounded-lg mt-4 border border-gray-700 flex flex-col">
                        <div className="flex items-center justify-between p-2 border-b border-gray-700 bg-black/20">
                            <div className="flex gap-1">
                                <button
                                    onClick={() => setViewMode('code')}
                                    className={`px-3 py-1 text-xs rounded transition-colors ${
                                        viewMode === 'code'
                                            ? 'bg-[#4ac94a] text-white font-semibold'
                                            : 'hover:bg-white/10'
                                    }`}
                                >
                                    Generated Code
                                </button>
                                <button
                                    onClick={() => setViewMode('diff')}
                                    className={`px-3 py-1 text-xs rounded transition-colors ${
                                        viewMode === 'diff'
                                            ? 'bg-[#4ac94a] text-white font-semibold'
                                            : 'hover:bg-white/10'
                                    }`}
                                >
                                    Diff
                                </button>
                            </div>
                            <span className="text-xs font-semibold text-[#4ac94a] animation-title-pulse">
                                {viewMode === 'diff' ? 'Comparing with Editor' : 'Final Output'}
                            </span>
                        </div>
                        <div className="p-3.5 max-h-72 overflow-y-auto">
                            {viewMode === 'code' ? (
                                <pre className="text-xs font-mono whitespace-pre-wrap text-slate-300">
                                    <code
                                        dangerouslySetInnerHTML={{
                                            __html: highlightMatches(codeToActOn, searchQuery || ''),
                                        }}
                                    />
                                </pre>
                            ) : (
                                <DiffViewer before={originalCode} after={codeToActOn} />
                            )}
                        </div>
                        <div className="p-2.5 border-t border-gray-700 flex gap-2">
                            <button
                                onClick={() => onCopyCode(codeToActOn)}
                                className="flex-1 bg-[#4ac94a] hover:bg-green-400 text-xs px-2 py-1.5 rounded transition-colors"
                            >
                                Copy Code
                            </button>
                            <button
                                onClick={() => onApplyCode(codeToActOn)}
                                className="flex-1 bg-[#5bc0de] hover:bg-cyan-400 text-xs px-2 py-1.5 rounded transition-colors"
                            >
                                Apply to Editor
                            </button>
                        </div>
                    </div>
                )}

                {filteredConsensus && filteredConsensus.allCandidates.length > 0 && (
                    <ConsensusPanel consensus={filteredConsensus} />
                )}
                {filteredGroundingChunks && filteredGroundingChunks.length > 0 && (
                    <GroundingPanel chunks={filteredGroundingChunks} />
                )}
            </div>
        </div>
    );
};
